export const BACKEND_DOMAIN = process.env.NEXT_PUBLIC_BACKEND_DOMAIN
export const BACKEND_URL = `${BACKEND_DOMAIN}/api/v1`

export const FRONTEND_URL = process.env.NEXT_PUBLIC_FRONTEND_URL

export const ENCRYPTION_SECRET = process.env.NEXT_PUBLIC_ENCRYPTION_SECRET